"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# -*- coding: utf-8 -*-
from setuptools import setup

APP = ['Flash_Uploader.py']
APP_NAME = "FlashUploader"
DATA_FILES = ['defaultpath.txt', 'avrdude', 'avrdude.conf', 'logo.icns', './release']

OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'logo.icns',
    'optimize': 2,
    'includes':['pyserial'],
    'frameworks':['./lib/libffi.7.dylib',
                  './lib/libtcl8.6.dylib',
                  './lib/libtk8.6.dylib'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Upload firmwares",
        'CFBundleIdentifier': "https://www.petoi.com/",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2022, Petoi LLC, All Rights Reserved"
        }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
