"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# -*- coding: utf-8 -*-
from setuptools import setup

APP = ['Flash_Uploader.py']
APP_NAME = "FlashUploader"
DATA_FILES = ['defaultpath.txt', 'avrdude','avrdude.conf','logo.icns']
OPTIONS = {
    'iconfile': 'logo.icns'
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
